name: "self test development-like"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn && yarn build && yarn build-storybook
    - uses: ./
      with: 
        projectToken: 5oy3iw6rkio
        token: ${{ secrets.GITHUB_TOKEN }}
        storybookBuildDir: storybook-static
