name: "Chromatic via action"
on: [push, pull_request, pull_request_review, pull_request_target]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: gcaw1ai2dgo